Nathalie & Destiny Pizza Bot
Technigo/project-pizza-bot pull request #29
Opened 2020-09-11 12:03 UTC by nathalienordstrom

Link to my deployed project:

My reflections on how this week's project turned out:

Things I'd like to have clarified or explained in more detail:

2020-09-16 15:00 UTC, EmOlsz requested changes
You chose pretty ambitious approach Nathalie & Destiny! Building "slideshow app" mechanism is very hard even to make it work, not mentioning about clean, semantic way of writing it. Nonetheless, you made it work and even added some interesting changes like pizza-as-radio-button, html visualisation and, lastly, slideshow effect.

Still, there is a lot of messy code and some rather random ways of writing your logic. Please, check out my comments below and fix as much of code as you can. Before I will be able to approve your project, I need to see part of those changes, which are :

1. Changing `img` tag from `<img></img>` to `<img />`
2. Changing `let` to `const`
3. Fixing indentation, commented code and empty lines

2020-09-16 15:00 UTC, EmOlsz commented on code/index.html
> +      rel="stylesheet"
Very nice code formatting :)

2020-09-16 15:00 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" type="text/css" href="style.css" />
Let's not forget about `./` in file path

2020-09-16 15:00 UTC, EmOlsz commented on code/index.html
> +    <img class="logga" src="https://images.vexels.com/media/users/3/128435/isolated/preview/3bba8cf18c7b31717c98231e7d6e736e-italian-pizza-logo-by-vexels.png" alt="logo" ></img>
`img` is self closing tag - it should look like this :

`<img />`

instead of :

`<img></img>`

2020-09-16 15:00 UTC, EmOlsz commented on code/index.html
> +          <section class="three_pizzas">
When naming classes, we should use `kebab-case` convention, not `snake_case` as you did, so it should look like `three-pizzas` rather than `three_pizzas`

2020-09-16 15:00 UTC, EmOlsz commented on code/index.html
> +            <label for="vegetarian">
If you nest `input` inside `label`, there is no need for `for="vegetarian"` attribute. We can either choose 

```
<label>
    That's my label
    <input />
</label>
```
or
```
<label for="vegetarian">That's my label</label>
<input id="vegetarian" />
```

2020-09-16 15:00 UTC, EmOlsz commented on code/index.html
> +                <img src="vegetarian.png" alt="Vegetarian Pizza" />
`./`

2020-09-16 15:00 UTC, EmOlsz commented on code/index.html
> +          <section class="pizzas_number">
Hmm... Don't you think that `<input type="radio" />` are not the best idea over here? What if I would like to order 11 pizzas? Not mentioning about how long your code is because of that.
Far better approach would be to create one `<input type="number" />`, where user can type amount he/she wants to order

2020-09-16 15:00 UTC, EmOlsz commented on code/index.html
> +    <script src="pizzabot.js"></script>
`./`

2020-09-16 15:00 UTC, EmOlsz commented on code/pizzabot.js
> +const gotoNext = () => {
Regarding content of this function - it's not the best idea to control behaviour of elements like that. HTML in general should be autonomous code, connected to JS only in crucial parts.
Moreover, if you want to disable any button after something happens (in this case, when `gotoNext()` or `gotoPrevious()` functions are called), we don't have to cover all of buttons and sections, but only the one which should change.

Nonetheless, this is far too complicated code, please take a look on my general comment above regarding that

2020-09-16 15:00 UTC, EmOlsz commented on code/pizzabot.js
> +  let orderName = document.querySelector('input[name="pizzaChoice"]:checked').value
`getOrderName()` function is triggered each time you click on one of radio buttons. Why not use `event` argument provided by JavaScript and check value of clicked button by `event.target.value`?
Alternatively you can just pass your custom argument there, let's say `getOrderName('vegetarian')` and then, in JS, just assign this value to `orderName` variable. It could look like this :

HTML:
`<input type="radio" value="vegetarian" onclick="getOrderName(event)" />`
or
`<input type="radio" value="vegetarian" onclick="getOrderName('vegetarian')" />`

JS:
```
const getOrderName = (event) => {
  let orderName = event.target.value;
}
```
or
```
const getOrderName = (pizzaType) => {
  let orderName = pizzaType;
}
```

2020-09-16 15:00 UTC, EmOlsz commented on code/pizzabot.js
> +  let orderName = document.querySelector('input[name="pizzaChoice"]:checked').value
Once again you are creating `orderName` variable. Why not creating it one time in global scope so you can access it from every function?

2020-09-16 15:00 UTC, EmOlsz commented on code/pizzabot.js
> +  let orderQuantity = document.querySelector('input[name="numberOrdered"]:checked').value
Same with orderQuantity - this variable could be created in global scope and being overwritten only one time - after we got exact value selected by user

2020-09-16 15:00 UTC, EmOlsz commented on code/pizzabot.js
> +  let totalPrice = orderQuantity * pizzaPrice
You are using a lot of `let` keyword, even though you never overwrite their values. You should use `const` instead.
General rule is that at the beginning all fo your variables should be created with `const` keyword. You should change them to `let` only after you find out you need to overwrite value of your variable somewhere in code

2020-09-16 15:00 UTC, EmOlsz commented on code/pizzabot.js
>  const pepperoni = "Pepperoni Pizza"
All of those should be at the top of JS file

2020-09-16 15:00 UTC, EmOlsz commented on code/pizzabot.js
> +document.getElementById("btn10").addEventListener("click", getConfirmation)
Once again - imagine doing same logic with one `<input type="number" />` instead of 10x `<input type="radio" />`

2020-09-16 15:00 UTC, EmOlsz commented on code/style.css
> +justify-content: space-evenly;
wrong indentation

2020-09-16 15:00 UTC, EmOlsz commented on code/style.css
> +  }
from here below you have wrong indents

2020-09-16 15:00 UTC, EmOlsz commented on code/style.css
> +    background-image: url(marble-2398946_1280.jpg);
Some browsers will not format that path because of lack of quotes. It's far more safe to define background property like this :

`background-image: url("marble-2398946_1280.jpg");`

2020-09-16 15:00 UTC, EmOlsz commented on code/style.css
> +    margin: 0px;
If value is equal to `0px`, you can omit `px` and just type `0`

2020-09-16 15:00 UTC, EmOlsz commented on code/style.css
> +  p {
Why styling by selectors? We should avoid that and focus mostly on styling by class name

2020-09-16 15:00 UTC, EmOlsz commented on code/style.css
> +  /* */
Some unused comment, let's delete it

2020-09-16 15:00 UTC, EmOlsz commented on code/style.css
> +  #first,
Definitely we should avoid styling by id as well

2020-09-16 15:00 UTC, EmOlsz commented on code/style.css
> +    margin: 0px 0 0 0;
we can write this line of code by shorthand - `margin: 0;`

2020-09-16 15:00 UTC, EmOlsz commented on code/style.css
> +
Let's delete these empty lines

2020-09-16 15:00 UTC, EmOlsz commented on code/style.css
> +  .numBtn:hover {
We should only use `kebab-case` naming pattern rather than `camelCase` when it comes to class names

2020-09-17 09:37 UTC, nathalienordstrom commented on code/index.html
> +    <link rel="stylesheet" type="text/css" href="style.css" />
do I need a . before the /?

2020-09-17 09:48 UTC, nathalienordstrom commented on code/index.html
> +            <label for="vegetarian">
why do I have to write That's my label?

2020-09-17 09:50 UTC, nathalienordstrom commented on code/index.html
> +                <img src="vegetarian.png" alt="Vegetarian Pizza" />
I have never seen ./ ? why do I have to write a dot there?

2020-09-17 09:55 UTC, nathalienordstrom commented on code/index.html
> +          <section class="pizzas_number">
Is it a okey way of writing it if we would like to have an maximum of ten pizzas, so we don't need to change the hole styling regarding that?

2020-09-17 09:56 UTC, nathalienordstrom commented on code/index.html
> +    <script src="pizzabot.js"></script>
i don´t know where to put it?

2020-09-17 10:06 UTC, nathalienordstrom commented on code/pizzabot.js
> +  let orderName = document.querySelector('input[name="pizzaChoice"]:checked').value
I don´t really follow what is the different outcome of is. What is the final diffrence?

2020-09-17 10:13 UTC, nathalienordstrom commented on code/pizzabot.js
> +  let orderName = document.querySelector('input[name="pizzaChoice"]:checked').value
I can't figur out how it would look?

2020-09-17 10:14 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" type="text/css" href="style.css" />
Yes, `./` sign means basically `THIS folder`. As I mentioned that during the lecture, from pragmatic point of view there is no difference between paths `style.css` and `./style.css`, but from semantic and clean-code point of view we should always include `./`

2020-09-17 10:15 UTC, EmOlsz commented on code/index.html
> +            <label for="vegetarian">
You don't have to write exactly this sentence :) What I meant is that you need to write something, no matter what.

2020-09-17 10:16 UTC, EmOlsz commented on code/index.html
> +                <img src="vegetarian.png" alt="Vegetarian Pizza" />
Check out my comment above. I talked about that during lectures, please check recordings from Week 2

2020-09-17 10:17 UTC, EmOlsz commented on code/index.html
> +          <section class="pizzas_number">
If you want to have maximum and minimum amounts, you can do that by validating your numeric input as well :

`<input type="number" min="1" max="10" />`

2020-09-17 10:17 UTC, EmOlsz commented on code/index.html
> +    <script src="pizzabot.js"></script>
Check comment above

2020-09-17 10:20 UTC, EmOlsz commented on code/pizzabot.js
> +  let orderName = document.querySelector('input[name="pizzaChoice"]:checked').value
There is not pragmatic difference, both yours and mine code work the same. The difference lays on HOW we write it - your approach is non-semantical

2020-09-17 10:20 UTC, EmOlsz commented on code/pizzabot.js
> +  let orderName = document.querySelector('input[name="pizzaChoice"]:checked').value
Same as in comment above :)

2020-09-17 10:23 UTC, nathalienordstrom commented on code/pizzabot.js
> +document.getElementById("btn10").addEventListener("click", getConfirmation)
But can I have the layout that is with one row of code as you typed?

2020-09-17 10:27 UTC, EmOlsz commented on code/pizzabot.js
> +document.getElementById("btn10").addEventListener("click", getConfirmation)
Yes, of course

2020-09-17 11:24 UTC, nathalienordstrom commented on code/index.html
> +            <label for="vegetarian">
Will the text come up somehwere or what is the purpose of the text?

2020-09-17 11:41 UTC, nathalienordstrom commented on code/index.html
> +          <section class="pizzas_number">
<!-- How many do you want  -->
        <div id="third">
          <h3>How many of <span id="pizzaChoice"></span> would you like?</h3>
          <section class="pizzas_number">
            <label for="btn1">
         **so like this**  **<input type="number" min="1" max="10" />**
**Insted of this?** **<input type="radio" id="btn1" name="numberOrdered" value="1" ./>**
              <div class="numBtn">1</div>
            </label>

2020-09-17 11:48 UTC, nathalienordstrom commented on code/index.html
> +          <section class="pizzas_number">
so I just replace this line:
 <input type="radio" id="btn1" name="numberOrdered" value="1" ./>

with
<input type="number" min="1" max="10" ./>

or do i deleta everything below line 91

2020-09-17 14:42 UTC, nathalienordstrom commented on code/index.html
> +            <label for="vegetarian">
I tried to write 
<label for="vegetarian">Vegetarian</label>
<input id="vegetarian" />

But then the word should up in ha weird place and I don´t want a word there. so can I just skip to have word there?

2020-09-17 14:46 UTC, nathalienordstrom commented on code/index.html
> +            <label for="vegetarian">
I tried to write the first code example you gave and the text that I wrote shows up and I don´t want a text there. So I just put 
```
<label> 
<input
type="radio"
                id="vegetarian"
                name="pizzaChoice"
                value="Vegetarian Pizza"
              />
</label> 
```

2020-09-17 14:46 UTC, nathalienordstrom commented on code/index.html
> +            <label for="vegetarian">
is that okey?

2020-10-01 19:30 UTC, EmOlsz approved these changes

2020-10-01 19:30 UTC, EmOlsz commented on code/index.html
> +            <label for="vegetarian">
Yes, that's main purpose of `label` - it informs user what the control next to it is about

2020-10-01 19:30 UTC, EmOlsz commented on code/index.html
> +          <section class="pizzas_number">
Yes, you need to delete all 10 radio buttons and replace them with only one numeric input

2021-03-11 09:09 UTC, closed without merging