Pizza Bot - Hanna Skeppe and Therese Lindén
Technigo/project-pizza-bot pull request #39
Opened 2020-09-11 13:53 UTC by Hanna-Skeppe

Link to my deployed project:
https://pizza-bot-hanna-and-therese.netlify.app/

My reflections on how this week's project turned out:
We are proud of that we accomplished this project together without any prior knowledge of Javascript. 

Things I'd like to have clarified or explained in more detail:
We think that it would have helped us if we had gotten some more practice in basic Javascript before doing this project. Going into this project without a basic understanding of Javascript was quite challenging. Maybe the material and the lecture could have been more connected to the task.

2020-09-17 10:01 UTC, EmOlsz requested changes
Congratulations Hanna & Therese, good job this week! Your code in general clean and predictable, as it should be :) That's the most important thing to learn from last week - how to use functions and connect them to HTML, and you've done it well! I like your visualisation in HTML and range slider, very ambitious of you. Take a look on my comments, I hope they will help you to be even better programmers :)

Before I will approve your project, I need you to remove `console.log()` occurrences from code, please fix that as soon as possible.

Congratulations! :)

2020-09-17 10:01 UTC, EmOlsz commented on code/index.html
> +    <link rel="apple-touch-icon-precomposed" href="pizza-152-296065.png">
Very good idea :)

2020-09-17 10:01 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" href="./style.css">
Thank you for `./` in file path!

2020-09-17 10:01 UTC, EmOlsz commented on code/index.html
> +          />
Great line breaks :)

2020-09-17 10:01 UTC, EmOlsz commented on code/index.html
> +              <option value="Vegetarian Pizza">Vegetarian Pizza</option>
`value` attribute should be a string without whitespaces, written in `camelCase` - it's because this is not information for human, only for computer :

`<option value="thisIsInfoForBackEnd">This is part displayed in the browser for users</option>`

2020-09-17 10:01 UTC, EmOlsz commented on code/index.html
> +          <input type="range" id="pizzaRangeSlider" class="pizza-range-slider" name="pizzaRangeSlider" min="0" max="8" value="1"
Clever idea, I'm happy you did something different here than usual `<input type="number" />`

2020-09-17 10:01 UTC, EmOlsz commented on code/index.html
> +      <img id="pizzaPhoto" src="eatingPizza.jpg" alt ="picture of selected pizza">
`./` missing

2020-09-17 10:01 UTC, EmOlsz commented on code/pizzabot.js
> +const validateOrderName = (orderName) =>{
There is an arrow function convention which says that if we pass to our function only one argument, we can omit parentheses `()`, and rather write :

`const validateOrderName = order => { ... }`

than

`const validateOrderName = (order) => { ... }`

Important thing to notice - this convention should be applied ONLY when we pass one argument. If we would do this with multiple arguments, it would cause `SyntaxError` to occur

2020-09-17 10:01 UTC, EmOlsz commented on code/pizzabot.js
> +    else return false;
Great job :)
Regarding clean code, there is also another convention, let me introduce you to it.
Apart from returning given thing from function, `return` keyword does one more thing - it automatically finishes function. That's why we mustn't write anything below `return`, because that code will never be executed (of course in your case we have code below `return true`, but it's inside if statement, so it wouldn't enter second statement in the first place).
Thanks to that feature of `return` keyword, we can write our function in slightly different, far more clean fashion :
```
const validateOrderName = order => {
  if (orderName === vegetarian || orderName === pepperoni || orderName === hawaiian) {
    return true;
  }
  return false;
}
```
As you can see, we are not writing else statement anymore. We can do that thanks to behaviour mentioned above; if result of if statement is `true`, we will execute `return true` code from line 18 and finish function. If, on the other hand, result of it is `false`, we will never enter line 18 and jump straight into line 20. After executing line 20 we will finish function same way :)

2020-09-17 10:01 UTC, EmOlsz commented on code/pizzabot.js
> +//console.log(validateOrderName);
Before pushing your code, check all commented stuff and delete it

2020-09-17 10:01 UTC, EmOlsz commented on code/pizzabot.js
> +   return orderTotal;
Very nice :) Another tip from my side - since we have only one line inside `calculateTotalCost` function, we can write it in "arrow function shorthand" :

`const calculateTotalCost = (quantity, price) => quantity * price;`

We can do that because in arrow functions we can omit curly brackets (`{}`) and `return` keyword if we only have one line of code inside.
For further reference on that subject, please check out https://www.w3schools.com/js/js_arrow_function.asp

2020-09-17 10:01 UTC, EmOlsz commented on code/style.css
> +  background: url(./pizza-dough.jpg) no-repeat center center fixed;
Some browsers will not format that path because of lack of quotes. It's far more safe to define background property like this :

background: url("./pizza-dough.jpg") no-repeat center center fixed;

2020-09-17 10:01 UTC, EmOlsz commented on code/style.css
> +  animation: neon1 1.5s ease-in-out infinite alternate;
Great! :)

2020-09-19 18:06 UTC, Hanna-Skeppe commented on code/index.html
> +      <img id="pizzaPhoto" src="eatingPizza.jpg" alt ="picture of selected pizza">
Fixed it now :)

2020-09-19 18:10 UTC, Hanna-Skeppe commented on code/pizzabot.js
> +const validateOrderName = (orderName) =>{
Fixed it now :)

2020-09-19 18:12 UTC, Hanna-Skeppe commented on code/index.html
> +              <option value="Vegetarian Pizza">Vegetarian Pizza</option>
Fixed now :)

2020-09-19 18:14 UTC, Hanna-Skeppe commented on code/pizzabot.js
> +    else return false;
Ok, thanks for the info Maks, we fixed it :)

2020-09-19 18:21 UTC, Hanna-Skeppe commented on code/pizzabot.js
> +   return orderTotal;
Thanks for the tip Maks. We tried to change the function according to what you suggested, but didn't get it to work. We will look in to this in future projects.

2020-09-19 18:24 UTC, Hanna-Skeppe commented
We have made the changes that you suggested. Get back to us if it is something we missed :)

2020-09-21 16:10 UTC, EmOlsz approved these changes

2021-03-11 09:09 UTC, closed without merging