Pizza bot: Nadia and Rebeka
Technigo/project-pizza-bot pull request #46
Opened 2020-09-12 15:00 UTC by rebkova

Link to my deployed project: pizz-a-licious.netlify.app 

My reflections on how this week's project turned out: We're happy with finished blue level requirements

Things I'd like to have clarified or explained in more detail: HTML-JS interaction. However, practice makes progress.

2020-09-18 08:33 UTC, HIPPIEKICK requested changes
Good job you two! Super that you allow the input to be case insensitive and that you are consistent with semi-colons. You need to make some additions to be approved. The validateOrderName() function works well, but you need to break the other code into functions as well as per Iteration 6 in the brief:

> ## **Iteration 6 - Add functions**
> Clean up your code by moving some code into functions and then calling that function when needed.
> The functions should all reflect the tasks we've completed so far. So, the functions should be:
> 1. `validateOrderName()` which should take the `orderName` variable as an argument and return `true` or `false` if the pizza is on the menu or not.
> 2. `calculateTotalCost()` which takes `orderQuantity` and `pizzaPrice` as arguments and returns the total cost for the order.
> 3. `calculateCookingTime()` which takes `orderQuantity` and returns the number of minutes it will take to finish the order.

Take a look at the stack overflow question I linked to as well. Reach out if you have any questions!

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/index.html
> +      <div class="content-area">
Do you need both of these `div`'s?

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/index.html
> +      <div class="box">
Do you need both of these?

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/pizzabot.js
> +//console.log(`Test if connection HTML-JS works: ${vegetarian}, ${hawaiian} and ${pepperoni}`);
Remove commented-out code before submitting for review

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/pizzabot.js
> +}
Take a look at this question on stack overflow to prevent the user from going forward if the pizza name is not valid:
https://stackoverflow.com/c/technigo/questions/1447/1475#1475

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/pizzabot.js
> +};
Super nice with `toLowerCase()`. Check your VSCode settings as you have 4 spaces instead of 2:
- Preferences
- Settings
- Search for "Tab Size" and change it to 2

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/pizzabot.js
> +var orderTotal;
Use `let` if you want to reassign the value

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/pizzabot.js
> +}
Also consider validating the ordername and store it in a variable to make the if-statement more readable:

```
const isPizzaOnMenu = validateOrderName(orderName)

if (isPizzaOnMenu) {
  /*...*/
}
```

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/pizzabot.js
> +    alert(`Great, I'll get started on your ${orderName}s right away, it will cost ${orderTotal} kr.`);
This should be broken out into another function, called something like `calculateTotalCost()` or `calculateOrderTotal()`

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/pizzabot.js
> +cookingTime = 20;
This should also be a function:

```
const calculateCookingTime = () => {
  /*...*/
}
```

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/style.css
> +  }
Indentation (the elements should be on the same level - now all elements except `*` are indented). This goes for the whole CSS-file.

```
* {
  padding: 0;
  margin: 0;
  box-sizing: border-box;
}

body {
  background: #eee;
  font-family: sans-serif;
}

.banner-area {
  width: 100%;
  height: 50vh;
  background-image: url(./pizza.jpg);
  filter: opacity(0.9);
  background-size: cover;
}
```

2020-09-18 08:33 UTC, HIPPIEKICK commented on code/pizzabot.js
> +//Function that tests whether the user input matches the pizza name
Great comment! When you're writing the other functions, you can start by making comments like these to clarify to yourselves what the function should do. E.g. for `calculateTotalCost()`
`//This function will calculate the total cost of the order by multiplying the orderQuantity and the pizzaPrice`

2020-09-20 19:17 UTC, rebkova commented
Changes have been implemented. The last update was 2020-09-20.

2020-09-23 08:35 UTC, HIPPIEKICK approved these changes

2021-03-11 09:09 UTC, closed without merging